### ISSUE TITLE
Unable to access runtime-native

### ISSUE THREAD

**Issue by arvind-iyer** [arenaxr/arena-services-docker#35]
Hi, 
I wanted to try setting up arenaxr locally, but it seems that this project uses SilverlineFramework/runtime-native which seems to be a private repository. Are there plans to make that service public? Do the authors have any suggestions on getting this up without it?

ArenaXR looks absolutely wonderful, great work! I plan on keeping up with it as it matures and progresses

**Comment by arvind-iyer** [comment]
Just realized it doesn't seem to be actually used by the docker-compose. Is it still required as a git submodule?

**Comment by nampereira** [comment]
Arvind, I'm sorry for not getting back to you sooner. Some of us in the team were taking a break. 

You are right, we removed `runtime-native` some time ago exactly to avoid this issue, but unfortunately forgot to remove the submodule.
